// Compiled P04 acceptance with independent task scope and no external adapters.
const {spawn,execFileSync,spawnSync}=require('node:child_process');const fs=require('node:fs');const {join}=require('node:path');const {randomBytes}=require('node:crypto');const assert=require('node:assert/strict');
const {smokePaths,stopProcess}=require('./smoke-paths.cjs');const {exe,dir}=smokePaths('dependency');let data=join(dir,'data'),daemon;
const id=()=>randomBytes(16).toString('hex');const raw=(...args)=>execFileSync(exe,[...args,'--data-dir',data],{encoding:'utf8'});const cli=(...args)=>JSON.parse(raw(...args));const refused=(...args)=>spawnSync(exe,[...args,'--data-dir',data],{encoding:'utf8'});const input=(name,v)=>{const p=join(dir,name+'.json');fs.writeFileSync(p,JSON.stringify(v));return p;};
async function start(){daemon=spawn(exe,['start','--data-dir',data],{stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let errors='';const timer=setTimeout(()=>reject(Error(errors)),10000);daemon.stderr.on('data',b=>errors+=b);daemon.stdout.once('data',()=>{clearTimeout(timer);resolve();});daemon.once('error',e=>{clearTimeout(timer);reject(e);});daemon.once('exit',c=>{clearTimeout(timer);reject(Error('daemon exit '+c+errors));});});}
(async()=>{try{
 cli('init');await start();cli('add','Root','--id','root','--status','active');cli('add','Own task','--id','alpha','--parent','root','--status','active');cli('add','Private prerequisite','--id','beta','--status','active');cli('add','Third project','--id','gamma','--status','active');
 const c=cli('contract','accept','alpha','--expected-task-revision','1','--file',input('contract',{previous:'none',objective:'Preserve accepted direction'}));
 const cp=cli('checkpoint','create','alpha','--expected-task-revision','1','--file',input('checkpoint',{previous:'none',contract_id:c.id,summary:'Meaningful planning progress',next_action:'Review the prerequisite',blockers:['Need the reviewed specification']}));
 const p=cli('progress','propose','alpha','--expected-task-revision','1','--file',input('proposal',{kind:'decision',contract_id:c.id,text:'A pending design choice'}));
 const request=(target,on,previous='none',op='add')=>({version:1,id:id(),target,depends_on:on,expected_task_revision:cli('state',target).revision,expected_prerequisite_revision:cli('state',on).revision,previous,op,reason:'Wait for reviewed prerequisite'});
 const r=request('alpha','beta');const file=input('dependency',r);const d=cli('dependency','add','alpha','--file',file);assert.equal(cli('dependency','list','alpha')[0].status,'pending');
 const r2=request('beta','gamma');cli('dependency','add','beta','--file',input('dependency-two',r2));const cycle=request('gamma','alpha');assert.notEqual(refused('dependency','add','gamma','--file',input('cycle',cycle)).status,0);
 const summary=()=>cli('progress','summary','alpha');let s=summary();assert.equal(s.items[0].checkpoint.id,cp.id);assert.equal(s.items[0].pending_decisions[0].id,p.id);assert.equal(s.items[0].next_action,cp.next_action);
 const before=cli('events');cli('progress','summary','--all','--sort','due','--limit','2');cli('dependency','show','alpha','--id',d.id);assert.deepEqual(cli('events'),before);
 const credential=join(dir,'reader.credential.json');const grant=cli('grant','issue','root','--name','Summary reader','--subtree','--expires',new Date(Date.now()+3600000).toISOString(),'--output',credential);
 const scoped=()=>cli('client','summary','root','--subtree','--sort','id','--limit','1','--credential',credential);const page=scoped();assert.equal(page.items[0].target,'alpha');assert(page.next_cursor);assert.equal(page.items[0].dependencies[0].status,'restricted');assert(!JSON.stringify(page).includes('Private prerequisite'));assert(!JSON.stringify(page).includes('depends_on'));
 assert.equal(cli('client','summary','root','--subtree','--sort','id','--limit','1','--cursor',page.next_cursor,'--credential',credential).items[0].target,'root');
 cli('complete','beta');assert.equal(summary().items[0].dependencies[0].status,'satisfied');assert.equal(cli('state','alpha').task.status,'active');
 assert.match(refused('client','summary','root','--subtree','--sort','id','--limit','1','--cursor',page.next_cursor,'--credential',credential).stderr,/409/);
 cli('reopen','beta');assert.equal(summary().items[0].dependencies[0].status,'pending');
 const stale={...request('gamma','beta'),expected_prerequisite_revision:1};assert.match(refused('dependency','add','gamma','--file',input('stale',stale)).stderr,/409/);
 const remove=request('alpha','beta',d.id,'remove');const removal=cli('dependency','remove','alpha','--file',input('remove',remove));assert.equal(cli('dependency','list','alpha').length,0);assert.deepEqual(cli('dependency','show','alpha','--id',d.id),d);assert.equal(removal.previous,d.id);
 cli('grant','revoke',grant.id);assert.match(refused('client','summary','root','--credential',credential).stderr,/403/);
 assert.deepEqual(cli('checkpoint','show','alpha'),cp);const state=cli('state');fs.writeFileSync(join(dir,'events.json'),JSON.stringify(cli('events'),null,2)+'\n');await stopProcess(daemon,'SIGKILL');await start();assert.deepEqual(cli('dependency','add','alpha','--file',file),d);cli('replay');assert.deepEqual(cli('state'),state);
 const snapshot=join(dir,'snapshot.db');cli('backup','--output',snapshot);await stopProcess(daemon);const source=data;data=join(dir,'restored');fs.mkdirSync(data);fs.copyFileSync(snapshot,join(data,'heimdall.db'));fs.copyFileSync(join(source,'types.yaml'),join(data,'types.yaml'));await start();assert.deepEqual(cli('state'),state);cli('replay');assert.deepEqual(cli('state'),state);assert.deepEqual(cli('dependency','add','alpha','--file',file),d);
 console.log(JSON.stringify({status:'passed',checks:['task dependency cycles/revisions/removal','checkpoint and pending decision summary','explicit sort and cursor binding','scope redaction and revocation','completion/reopen changes derived status only','read-only summaries','SIGKILL/restart exact receipts','replay and backup restore'],data:dir},null,2));
}finally{await stopProcess(daemon);}})().catch(e=>{console.error(e);process.exitCode=1;});
