// W02 compiled CLI, synthetic compositor IPC, restart/replay/backup acceptance.
const {spawn,execFileSync,spawnSync}=require('node:child_process');const fs=require('node:fs');const {join}=require('node:path');const {randomBytes}=require('node:crypto');const assert=require('node:assert/strict');const os=require('node:os');
const {smokePaths,stopProcess}=require('./smoke-paths.cjs');const {exe,dir}=smokePaths('viewport');let data=join(dir,'data'),daemon,fake;const socketDir=fs.mkdtempSync(join(os.tmpdir(),'heimdall-hypr-'));
const id=()=>randomBytes(16).toString('hex');const raw=(...args)=>execFileSync(exe,[...args,'--data-dir',data],{encoding:'utf8'});const cli=(...args)=>JSON.parse(raw(...args));const refused=(...args)=>spawnSync(exe,[...args,'--data-dir',data],{encoding:'utf8'});const input=(name,v)=>{const p=join(dir,name+'.json');fs.writeFileSync(p,JSON.stringify(v));return p;};
const waitReady=process=>new Promise((resolve,reject)=>{let errors='';const timer=setTimeout(()=>reject(Error(errors||'ready timeout')),10000);process.stderr.on('data',b=>errors+=b);process.stdout.once('data',()=>{clearTimeout(timer);resolve();});process.once('error',e=>{clearTimeout(timer);reject(e);});process.once('exit',c=>{clearTimeout(timer);reject(Error('process exit '+c+errors));});});
async function start(){daemon=spawn(exe,['start','--data-dir',data],{stdio:['ignore','pipe','pipe']});await waitReady(daemon);}
const window=(stableId,address,workspace=1,name='planning')=>({stableId,address,pid:123,class:'same-app',title:'Same title',mapped:true,monitor:0,workspace:{id:workspace,name},at:[10,20],size:[800,600]});
const fixture={version:{version:'0.56.2',dirty:false},monitors:[{id:0,name:'SYNTHETIC-1',x:0,y:0,width:1920,height:1080,scale:1,transform:0,activeWorkspace:{id:1}}],workspaces:[{id:1,name:'planning',monitor:'SYNTHETIC-1',monitorID:0},{id:2,name:'review',monitor:'SYNTHETIC-1',monitorID:0}],clients:[window('18000001','0x64'),window('18000002','0x65')]};
(async()=>{try{
 cli('init');await start();assert.equal(cli('viewport','status').observation.selected,false);
 if(process.platform!=='linux'){assert.notEqual(refused('viewport','probe','--socket-dir','/synthetic/unsupported').status,0);console.log(JSON.stringify({status:'passed',platform:process.platform,checks:['unsupported native adapter is explicit','daemon remains usable']}));return;}
 const stateFile=input('compositor',fixture),audit=join(dir,'ipc-reads.txt');fake=spawn('python3',[join(__dirname,'hyprland-fixture.py'),socketDir,stateFile,audit],{stdio:['pipe','pipe','pipe']});await waitReady(fake);
 cli('add','Viewport task','--id','alpha','--status','active');cli('add','Other task','--id','beta','--status','active');
 const surface=id();const m=cli('workspace','accept','alpha','--expected-task-revision','1','--file',input('manifest',{previous:'none',name:'Planning',surfaces:[{id:surface,kind:'terminal',label:'Shell',required:true,restore_policy:'manual'}]}));
 const probe=cli('viewport','probe','--socket-dir',socketDir);assert(probe.fresh);assert.equal(probe.snapshot.windows.length,2);
 const select={version:1,id:id(),op:'select',previous:'none',source:{socket_dir:socketDir,host:probe.snapshot.host,epoch:probe.snapshot.source_epoch}};const source=cli('viewport','select','--file',input('select',select));
 const inventory=cli('viewport','inventory');assert(inventory.fresh);
 const r={version:1,id:id(),op:'bind',previous:'none',target:'alpha',expected_task_revision:1,binding:{manifest_id:m.id,surface_id:surface,source_id:source.id,snapshot_id:inventory.snapshot.id,window:inventory.snapshot.windows[0].identity}};
 const file=input('bind',r);const bound=cli('viewport','bind','alpha','--file',file);let view=cli('viewport','list','alpha');assert.equal(view.surfaces[0].status,'observed');assert.equal(view.surfaces[0].window.identity.stable_id,'18000001');assert.equal(cli('viewport','list','beta').surfaces.length,0);
 fixture.clients[0]=window('18000001','0x64',2,'review');input('compositor',fixture);fake.stdin.write('movewindowv2>>64,2,review\n');assert.equal(cli('viewport','list','alpha').surfaces[0].window.workspace_id,2);
 fake.stdin.write('gap\n');await new Promise(r=>setTimeout(r,100));assert(cli('viewport','inventory').fresh);
 const credential=join(dir,'reader.credential.json');cli('grant','issue','alpha','--name','No desktop authority','--expires',new Date(Date.now()+3600000).toISOString(),'--output',credential);
 const ep=JSON.parse(fs.readFileSync(join(data,'endpoint.json'))),reader=JSON.parse(fs.readFileSync(credential)),browser=JSON.parse(fs.readFileSync(join(data,'browser-endpoint.json')));
 for(const token of [reader.token,browser.token]){const res=await fetch(ep.url+'/workspace/viewport/inventory',{headers:{authorization:'Bearer '+token}});assert.equal(res.status,401);}
 const state=cli('state');fs.writeFileSync(join(dir,'events.json'),JSON.stringify(cli('events'),null,2)+'\n');await stopProcess(daemon,'SIGKILL');await start();assert.equal(cli('viewport','status').source_head,source.id);assert.equal(cli('viewport','list','alpha').surfaces[0].status,'observed');
 cli('replay');assert.deepEqual(cli('state'),state);assert.deepEqual(cli('viewport','bind','alpha','--file',file),bound);
 const snapshot=join(dir,'snapshot.db');cli('backup','--output',snapshot);await stopProcess(daemon);const original=data;data=join(dir,'restored');fs.mkdirSync(data);fs.copyFileSync(snapshot,join(data,'heimdall.db'));fs.copyFileSync(join(original,'types.yaml'),join(data,'types.yaml'));await start();assert.deepEqual(cli('state'),state);assert.equal(cli('viewport','list','alpha').surfaces[0].status,'observed');
 fixture.clients=[window('18000009','0x64')];input('compositor',fixture);assert.equal(cli('viewport','list','alpha').surfaces[0].status,'missing');assert.deepEqual(cli('viewport','bind','alpha','--file',file),bound);
 const unbind={version:1,id:id(),op:'unbind',previous:bound.id,target:'alpha',expected_task_revision:1,binding:{manifest_id:m.id,surface_id:surface}};cli('viewport','unbind','alpha','--file',input('unbind',unbind));cli('viewport','stop','--file',input('stop',{version:1,id:id(),op:'stop',previous:source.id}));assert.equal(cli('viewport','status').observation.selected,false);
 assert(fs.readFileSync(audit,'utf8').trim().split('\n').every(v=>['j/clients','j/monitors','j/workspaces','j/version'].includes(v)));
 console.log(JSON.stringify({status:'passed',checks:['explicit selection and duplicate title binding','named workspace movement','event disconnect/reconciliation','scoped and browser credentials refused','SIGKILL/restart preserves native identity','inert replay and exact retries','backup restore','address reuse stays unowned','explicit unbind/stop','fixed read-only IPC vocabulary'],data:dir},null,2));
}finally{await stopProcess(daemon);await stopProcess(fake);fs.rmSync(socketDir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
