type Task = {id:string;title:string;status:string;parent?:string;next_action?:string;done:{text:string};subtasks?:{id:string;title:string;status:string}[]};
type TaskRecord = {task:Task;revision:number;workflow:{success_statuses:string[];dropped_statuses:string[]}};
type Snapshot = {tasks:TaskRecord[];target:string;revision:number;task_count:number;pending_reviews:number;checkpoint_count:number;truncated:boolean};
type Proposal = {id:string;target:string;status:string;evidence:string[]};
type Evidence = {id:string;status:string;outcome:string;reason?:string;started_at:string;finished_at?:string;evaluator_id:string;output_bytes?:number};
type Detail = {context:{task:TaskRecord;target:string;resume_status:string;contracts:{objective:string;constraints:string[];target:string}[];decisions:{text:string}[];checkpoint?:{summary:string;next_action:string;blockers:string[]};issues:{code:string;detail:string}[];resources:{resource:{id:string;path:string;kind:string};status:string}[]};evidence:Evidence[];invalidations:Record<string,{reason:string}>;proposals:Proposal[];checks:{id:string;kind:string;status:string}[];revision:number;truncated:boolean};
const el = <T extends HTMLElement=HTMLElement>(id:string):T => {const value=document.getElementById(id);if(!value)throw Error(`Missing element: ${id}`);return value as T;};
const make = <K extends keyof HTMLElementTagNameMap>(tag:K,text?:string,className?:string):HTMLElementTagNameMap[K] => {const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
let csrf="",cursor="",selected="",snapshot:Snapshot|undefined,busy=false,selectionVersion=0,sessionVersion=0;
function showError(message:string){el("error").textContent=message;el("error").hidden=!message;}
function login(){csrf="";cursor="";snapshot=undefined;selectionVersion++;sessionVersion++;el("detail").replaceChildren();el("tasks").replaceChildren();el("login").hidden=false;el("workspace").hidden=true;el("logout").hidden=true;el("connection").textContent="Sign-in required";}
async function api<T>(path:string,body?:unknown):Promise<T>{
 const response=await fetch(`/ui/${path}`,{method:body===undefined?"GET":"POST",credentials:"same-origin",headers:body===undefined?{}:{"Content-Type":"application/json","X-Heimdall-CSRF":csrf},body:body===undefined?undefined:JSON.stringify(body)});
 const value=await response.json();if(!response.ok){if(response.status===401)login();if(response.status===409)cursor="";throw Error(value.error||`Request failed (${response.status})`);}return value as T;
}
function badge(text:string,tone=""){return make("span",text,`badge ${tone}`);}
function panel(title:string){const node=make("section",undefined,"panel");node.append(make("h3",title));return node;}
function activate(){el("login").hidden=true;el("workspace").hidden=false;el("logout").hidden=false;el("connection").textContent="Connected locally";}
function renderTasks(){
 if(!snapshot)return;const query=el<HTMLInputElement>("search").value.trim().toLowerCase();const list=el("tasks");list.replaceChildren();
 for(const record of snapshot.tasks){const task=record.task;if(query&&!`${task.title} ${task.status}`.toLowerCase().includes(query))continue;const button=make("button",undefined,`task ${selected.split("#")[0]===task.id?"selected":""}`);button.setAttribute("aria-current",selected.split("#")[0]===task.id?"true":"false");button.append(make("strong",task.title),make("small",`${task.status}${task.parent?" · subtask":" · workstream"}`));button.onclick=()=>{selected=task.id;renderTasks();void loadDetail();};list.append(button);}
 if(!list.childElementCount)list.append(make("p","No matching tasks.","empty"));if(snapshot.truncated)list.append(make("p","Showing the first 200 tasks. Use the CLI for the complete list.","muted"));
}
function renderSnapshot(value:Snapshot){
 snapshot=value;activate();el("workspace-title").textContent=value.tasks.find(r=>r.task.id===value.target)?.task.title||"Your workstream";
 const metrics=el("metrics");metrics.replaceChildren();const active=value.tasks.filter(r=>![...r.workflow.success_statuses,...r.workflow.dropped_statuses].includes(r.task.status)).length;
 for(const [count,label] of [[value.task_count,"Tasks in scope"],[active,value.truncated?"Active in this page":"Active tasks"],[value.checkpoint_count,"Saved checkpoints"],[value.pending_reviews,"Awaiting review"]]){const metric=make("div",undefined,"metric");metric.append(make("strong",String(count)),make("span",String(label)));metrics.append(metric);}
 if(!selected||!value.tasks.some(r=>r.task.id===selected.split("#")[0]))selected=value.target;renderTasks();
}
function renderDetail(value:Detail){
 const {context}=value;const task=context.task.task;const container=el("detail");container.replaceChildren();
 container.append(badge(task.status),badge(context.resume_status==="ready"?"Ready to resume":"Review context",context.resume_status==="ready"?"":"warn"));
 const step=selected.includes("#")?task.subtasks?.find(s=>s.id===selected.split("#")[1]):undefined;
 container.append(make("h2",step?`${task.title} / ${step.title}`:task.title));
 const currentContract=context.contracts.find(c=>c.target===selected);container.append(make("p",currentContract?.objective||task.done.text||"No acceptance criteria recorded."));
 if(task.next_action)container.append(make("p",`Next action: ${task.next_action}`));
 if(context.issues.length){const issues=panel("Needs attention");for(const issue of context.issues)issues.append(make("p",issue.detail,"muted"));container.append(issues);}
 const continuity=panel("Last saved progress");if(context.checkpoint){continuity.append(make("p",context.checkpoint.summary),make("p",`Continue with: ${context.checkpoint.next_action}`));for(const blocker of context.checkpoint.blockers)continuity.append(badge(blocker,"warn"));}else continuity.append(make("p","No checkpoint yet. Save progress through the CLI or an authorized MCP client.","muted"));container.append(continuity);
 const direction=panel("Accepted direction");const constraints=context.contracts.flatMap(c=>c.constraints);if(!constraints.length&&!context.decisions.length)direction.append(make("p","No accepted constraints or decisions recorded.","muted"));const list=make("ul");for(const text of [...constraints,...context.decisions.map(d=>d.text)])list.append(make("li",text));direction.append(list);container.append(direction);
 if(task.subtasks?.length){const steps=panel("Steps");for(const s of task.subtasks){const button=make("button",`${s.title} · ${s.status}`);button.onclick=()=>{selected=`${task.id}#${s.id}`;void loadDetail();};const row=make("div",undefined,"actions");row.append(button);steps.append(row);}if(step){const back=make("button","Back to task");back.onclick=()=>{selected=task.id;void loadDetail();};steps.append(back);}container.append(steps);}
 const evidencePanel=panel("Completion evidence");evidencePanel.append(make("p","Recorded observations are rechecked against current inputs before accepting completion. A passing test does not complete the task.","muted"));
 for(const check of value.checks)evidencePanel.append(badge(`${check.kind}: ${check.status}`,check.status==="matched"?"":"warn"));
 if(!value.evidence.length)evidencePanel.append(make("p","No evaluator results yet.","muted"));
 for(const evidence of value.evidence){const card=make("div",undefined,"card");const invalid=value.invalidations[evidence.id];const label=invalid?"Invalidated":evidence.status==="started"?"Evaluation in progress":evidence.outcome==="matched"?"Recorded pass":evidence.outcome==="not_matched"?"Check did not pass":"Outcome unknown";card.append(badge(label,invalid||evidence.outcome!=="matched"?"warn":""),make("p",invalid?.reason||evidence.reason||"Observed against the recorded resource versions."),make("small",new Date(evidence.finished_at||evidence.started_at).toLocaleString(),"muted"));const details=make("details");details.append(make("summary","Provenance"),make("pre",JSON.stringify(evidence,null,2)));card.append(details);evidencePanel.append(card);}container.append(evidencePanel);
 const review=panel("Review completion");const pending=value.proposals.filter(p=>p.status==="pending");if(!pending.length)review.append(make("p","No completion proposal is waiting for review.","muted"));
 for(const proposal of pending){const card=make("div",undefined,"card");card.append(make("p","The recorded checks support completing this target. Accepting revalidates the evidence and records your decision."));const actions=make("div",undefined,"actions");for(const action of ["accept","reject"]){const button=make("button",action==="accept"?"Accept completion":"Reject proposal",action==="accept"?"primary":"");button.onclick=async()=>{button.disabled=true;try{await api("review",{id:crypto.randomUUID().replaceAll("-",""),proposal:proposal.id,action,revision:value.revision});showError("");cursor="";await refresh();}catch(error){showError(String(error));await loadDetail();}finally{button.disabled=false;}};actions.append(button);}card.append(actions);review.append(card);}container.append(review);
 const capabilities=panel("Connected capabilities");capabilities.append(make("p","Task state, checkpoints, scoped MCP and evidence review are available. Browser outcome verification, Braid retrieval and automatic continuation are still in development.","muted"));container.append(capabilities);
 if(value.truncated)container.append(make("p","Showing the latest 50 history records. Full history remains available through the CLI.","muted"));
 const details=make("details");details.append(make("summary","Task and resource details"),make("pre",JSON.stringify({target:selected,revision:value.revision,resources:context.resources},null,2)));container.append(details);el("boundary").textContent=`Task revision ${context.task.revision}`;
}
async function loadDetail(){if(!selected||!csrf)return;const version=++selectionVersion;try{const result=await api<Detail>(`task?target=${encodeURIComponent(selected)}`);if(version===selectionVersion)renderDetail(result);}catch(error){if(version===selectionVersion){el("detail").replaceChildren(make("h2","Context unavailable"),make("p",String(error)));showError(String(error));}}}
async function refresh(){if(busy||!csrf)return;busy=true;const version=sessionVersion;try{const value=await api<{changed:boolean;cursor:string;snapshot?:Snapshot}>(`feed?cursor=${encodeURIComponent(cursor)}`);if(version!==sessionVersion||!csrf)return;cursor=value.cursor;if(value.snapshot){renderSnapshot(value.snapshot);await loadDetail();}if(version===sessionVersion&&csrf)el("connection").textContent="Connected locally";}catch(error){if(version===sessionVersion&&csrf){el("connection").textContent="Connection needs attention";showError(String(error));}}finally{busy=false;}}
el<HTMLFormElement>("login-form").onsubmit=async event=>{event.preventDefault();try{const result=await api<{csrf:string;target:string}>("bootstrap",{code:el<HTMLInputElement>("code").value.trim()});csrf=result.csrf;selected=result.target;el<HTMLInputElement>("code").value="";showError("");activate();await refresh();}catch(error){showError(String(error));}};
el("logout").onclick=async()=>{try{await api("logout",{});login();showError("");}catch(error){showError(String(error));}};
el("refresh").onclick=()=>{showError("");cursor="";void refresh();};el<HTMLInputElement>("search").oninput=renderTasks;
void (async()=>{try{const session=await api<{csrf:string;target:string}>("session");csrf=session.csrf;selected=session.target;activate();await refresh();}catch{login();}})();
setInterval(()=>{if(!document.hidden)void refresh();},5000);
